#!/bin/bash
# mdd-sim-gateway — macOS native launcher for the control plane (Phase 1).
#
# Runs the FastAPI control surface directly on the host (no Docker):
#   - venv Python with control/requirements.txt installed
#   - state under $MDD_DATA (default ~/mdd-macos-build/data)
#   - self-signed TLS auto-generated by control/run.py on first boot
#
# Usage:
#   host/macos/run-control.sh [port]        # default port 8443, bind 127.0.0.1
#
# Env overrides:
#   MDD_VENV, MDD_DATA, MDD_WEBUI, MDD_HTTP_PORT, MDD_BIND, MDD_ADVERTISE_ADDR
#   PYSCARD_PCSC_LIB — point pyscard at the self-built pcsc-lite client library
#     (needed for the vpcd virtual reader; leave unset to use PCSC.framework):
#     PYSCARD_PCSC_LIB="$HOME/mdd-macos-build/stage/usr/local/lib/libpcsclite.1.dylib"
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
VENV="${MDD_VENV:-$HOME/mdd-macos-build/venv}"

if [ ! -x "$VENV/bin/python" ]; then
    echo "venv not found at $VENV (override with MDD_VENV)" >&2
    exit 1
fi

export MDD_DATA="${MDD_DATA:-$HOME/mdd-macos-build/data}"
export MDD_WEBUI="${MDD_WEBUI:-$REPO/webui/dist}"
export MDD_HTTP_PORT="${MDD_HTTP_PORT:-${1:-8443}}"
# Bind localhost by default on macOS: the native port has no reverse proxy in
# front and the engine containers (Linux Docker semantics) do not exist here.
export MDD_BIND="${MDD_BIND:-127.0.0.1}"

mkdir -p "$MDD_DATA"
exec "$VENV/bin/python" "$REPO/control/run.py"
